openapi: 3.1.0
info:
  title: User API
  description: API for managing users, including user registration, retrieval, and deletion.
  version: 1.0.0
  license:
    name: Apache 2.0
    url: https://www.apache.org/licenses/LICENSE-2.0.html
servers:
  - url: http://localhost
security:
  - ApiKeyAuth: []
paths:
  /user:
    $ref: './paths/user.yml'
  /register:
    $ref: './paths/register.yml'
  /delete:
    $ref: './paths/delete.yml'
components:
  schemas:
    user:
      $ref: './components/schemas/user.yml#/user'
    successWithUser:
      $ref: './components/schemas/success.yml#/successWithUser'
    success:
      $ref: './components/schemas/success.yml#/default'
    error:
      $ref: './components/schemas/error.yml#/default'
    userRequestBody:
      $ref: './components/requestBody/user.yml#/email'
    registerRequestBody:
      $ref: './components/requestBody/register.yml#/userWithoutId'
    delteRequestBody:
      $ref: './components/requestBody/delete.yml#/email'
  securitySchemes:
    ApiKeyAuth:
      type: apiKey
      in: header
      name: X-API-Key